# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: HNU DailyClockin

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
  - cron: '15 16 * * *'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Clockin
      env:
        LOGIN_ID: ${{secrets.LOGIN_ID}}
        LOGIN_PASSWORD: ${{secrets.LOGIN_PASSWORD}}
        BAIDU_API_KEY: ${{secrets.BAIDU_API_KEY}} 
        BAIDU_SECRET_KEY: ${{secrets.BAIDU_SECRET_KEY}}
        SERVERCHAN_SCKEY: ${{secrets.SERVERCHAN_SCKEY}}
      run:
        python Clockin.py
